// snapjudge tokenizer regression: encode() pinned to the committed fixture.
// Fixtures lock OUR tokenizer's output (self-generated by tests/gen_fixtures.cpp
// after external parity was proven during development).
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "doctest/doctest.h"

#include <fstream>
#include <string>
#include <vector>

#include "nlohmann/json.hpp"
#include "snapjudge/tokenizer.hpp"

using snapjudge::Tokenizer;
using nlohmann::ordered_json;

static std::string golden_dir() {
  if (const char* g = std::getenv("SNAPJUDGE_GOLDEN_DIR")) return g;
  return "tests/golden";
}
static std::string tiny_ckpt() {
#ifdef SNAPJUDGE_TINY_CKPT
  return SNAPJUDGE_TINY_CKPT;
#else
  return "build/tiny-ckpt";
#endif
}

TEST_CASE("tokenizer regression vs committed fixture (tiny BPE)") {
  std::ifstream gf(golden_dir() + "/tokenizer_tiny.json");
  REQUIRE(gf.good());
  ordered_json g;
  gf >> g;

  auto tok = Tokenizer::from_dir(tiny_ckpt() + "/tokenizer");
  const ordered_json sp = g["special"];
  CHECK(tok->cls_id == sp["cls"].get<int>());
  CHECK(tok->sep_id == sp["sep"].get<int>());
  CHECK(tok->pad_id == sp["pad"].get<int>());
  CHECK(tok->mask_id == sp["mask"].get<int>());
  CHECK(tok->mask_token == sp["mask_token"].get<std::string>());

  for (const auto& c : g["cases"]) {
    auto got = tok->encode(c["text"].get<std::string>());
    std::vector<int> want = c["ids"].get<std::vector<int>>();
    CHECK(std::vector<int>(got.begin(), got.end()) == want);
  }
}
