#!/usr/bin/env python3
"""snapjudge Unicode table generator.

Emits unicode_tables.inc consumed by snapjudge/src/unicode.cpp. Uses Python's
unicodedata at build time so the C++ runtime needs no ICU.

Tables emitted (all sorted, binary-searchable):
  ALPHA_RANGES  ranges where str.isalpha()
  DIGIT         codepoints with category Nd
  SPACE_RANGES  ranges where str.isspace()  (== Python re \s on str)
  WORD_RANGES   ranges where the char matches Python re \w minus digits
                and '_'  (== [^\W\d_] with re.UNICODE on a str)
  COMBINING     codepoints with unicodedata.combining() != 0
  LOWER/UPPER   full-case mappings (str.lower/upper), incl. multi-char
  DECOMP        canonical decompositions (recursive-able)
  COMP          canonical composition pairs (non-excluded)
  CCC           canonical combining classes
"""
import sys
import unicodedata

UNICODE_MAX = 0x10FFFF


def ch(cp):
    return chr(cp)


def ranges_of(pred):
    out, lo = [], None
    for cp in range(UNICODE_MAX + 1):
        ok = pred(cp)
        if ok and lo is None:
            lo = cp
        elif not ok and lo is not None:
            out.append((lo, cp - 1))
            lo = None
    if lo is not None:
        out.append((lo, UNICODE_MAX))
    return out


def main(out_path):
    alpha = ranges_of(lambda cp: ch(cp).isalpha())  # Python semantics (lang.py)
    # Regex-class tables for the HF tokenizer splitter (Rust regex semantics):
    #   \p{L} = category L*, \p{N} = Nd/Nl/No, \s = White_Space property.
    # Python's str.isspace() additionally matches \x1c-\x1f, so lang.py's \s
    # keeps the Python table while the tokenizer uses the White_Space one.
    letter = ranges_of(lambda cp: unicodedata.category(ch(cp)).startswith("L"))
    number = ranges_of(lambda cp: unicodedata.category(ch(cp)).startswith("N"))
    digit = [cp for cp in range(UNICODE_MAX + 1) if unicodedata.category(ch(cp)) == "Nd"]
    space = ranges_of(lambda cp: ch(cp).isspace())
    ws = [(0x09, 0x0D), (0x20, 0x20), (0x85, 0x85), (0xA0, 0xA0), (0x1680, 0x1680),
          (0x2000, 0x200A), (0x2028, 0x2029), (0x202F, 0x202F), (0x205F, 0x205F),
          (0x3000, 0x3000)]

    # [^\W\d_]: an identifier char that is a letter or a mark (Python \w on str
    # covers letters, digits, marks and '_').
    def word_nodigit_underscore(cp):
        c = ch(cp)
        if c == "_" or unicodedata.category(c) == "Nd":
            return False
        cat = unicodedata.category(c)
        return c.isalpha() or cat in ("Mn", "Mc", "Me", "Lm", "Nl")

    word = ranges_of(word_nodigit_underscore)

    # Python re \w under UNICODE: letters, digits, marks, '_'. Used by lang.py's
    # identifier regex [\w-]*([.@][\w-]+)+ and the [^\W\d_] word regex guard.
    import re as _re
    _w = _re.compile(r"\w")
    wordchar = ranges_of(lambda cp: bool(_w.match(ch(cp))))
    combining = [cp for cp in range(UNICODE_MAX + 1) if unicodedata.combining(ch(cp))]

    lower, upper = [], []
    for cp in range(UNICODE_MAX + 1):
        c = ch(cp)
        lo, up = c.lower(), c.upper()
        if lo != c:
            lower.append((cp, lo))
        if up != c:
            upper.append((cp, up))

    decomp, ccc = {}, {}
    for cp in range(UNICODE_MAX + 1):
        c = ch(cp)
        cls = unicodedata.combining(c)
        if cls:
            ccc[cp] = cls
        d = unicodedata.decomposition(c)
        if d and not d.startswith("<"):
            decomp[cp] = [int(x, 16) for x in d.split()]

    # Composition exclusions: a canonical pair maps back to cp only if NFC of
    # the decomposed string round-trips AND the decomposition is a pair.
    comp = {}
    for cp, parts in decomp.items():
        if len(parts) != 2:
            continue
        joined = "".join(chr(p) for p in parts)
        if unicodedata.normalize("NFC", joined) == ch(cp):
            comp[(parts[0], parts[1])] = cp

    with open(out_path, "w") as f:
        f.write("// GENERATED by snapjudge/python/gen_unicode.py -- do not edit\n")
        f.write("// Included inside `namespace snapjudge` after the table struct\n")
        f.write("// declarations in src/unicode.cpp; opens unicode_tables only.\n")
        f.write("namespace unicode_tables {\n")

        def emit_ranges(name, data):
            f.write(f"static const Range {name}[] = {{\n")
            for lo, hi in data:
                f.write(f"  {{0x{lo:X},0x{hi:X}}},\n")
            f.write("};\n")
            f.write(f"static const size_t {name}_N = {len(data)};\n")

        def emit_cps(name, data):
            f.write(f"static const char32_t {name}[] = {{\n")
            for i, cp in enumerate(data):
                f.write(f"0x{cp:X}," + ("\n" if i % 16 == 15 else ""))
            f.write("\n};\n")
            f.write(f"static const size_t {name}_N = {len(data)};\n")

        emit_ranges("ALPHA", alpha)
        emit_ranges("LETTER", letter)
        emit_ranges("NUMBER", number)
        emit_cps("DIGIT", digit)
        emit_ranges("SPACE", space)
        emit_ranges("WS", ws)
        emit_ranges("WORD", word)
        emit_ranges("WORDCHAR", wordchar)
        emit_cps("COMBINING", combining)

        def emit_case(name, pairs):
            f.write(f"static const CaseMap {name}[] = {{\n")
            for cp, s in pairs:
                cps = ",".join(f"0x{ord(c):X}" for c in s)
                f.write(f"  {{0x{cp:X},{{{cps}}},{len(s)}}},\n")
            f.write("};\n")
            f.write(f"static const size_t {name}_N = {len(pairs)};\n")

        emit_case("LOWER", lower)
        emit_case("UPPER", upper)

        f.write("static const Decomp DECOMP[] = {\n")
        for cp, parts in sorted(decomp.items()):
            vals = ",".join(f"0x{p:X}" for p in parts)
            f.write(f"  {{0x{cp:X},{{{vals}}},{len(parts)}}},\n")
        f.write("};\n")
        f.write(f"static const size_t DECOMP_N = {len(decomp)};\n")

        f.write("static const CompPair COMP[] = {\n")
        for (a, b), cp in sorted(comp.items()):
            f.write(f"  {{0x{a:X},0x{b:X},0x{cp:X}}},\n")
        f.write("};\n")
        f.write(f"static const size_t COMP_N = {len(comp)};\n")

        f.write("static const CccEntry CCC[] = {\n")
        for cp, cls in sorted(ccc.items()):
            f.write(f"  {{0x{cp:X},{cls}}},\n")
        f.write("};\n")
        f.write(f"static const size_t CCC_N = {len(ccc)};\n")

        f.write("} // namespace unicode_tables\n")

    total = map(len, (alpha, letter, number, digit, space, ws, word, wordchar, combining, lower, upper, decomp, comp, ccc))
    print("gen_unicode: %d entries -> %s" % (sum(total), out_path))


if __name__ == "__main__":
    main(sys.argv[1])
