#!/usr/bin/env python3
"""snapjudge dev tool: build the committed test fixtures.

Unlike the earlier parity goldens (which pinned to an external reference
implementation), these fixtures lock snapjudge's own current outputs as
regression fixtures. Generated ONCE with HF tokenizers (public library, not
part of snapjudge) for the tokenizer ids; the rest are self-generated.
"""
import json
import os

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "tests", "golden")
os.makedirs(OUT, exist_ok=True)

TEXTS = [
    "I was charged twice, please refund my money.",
    "Refactor this service to use fewer tokens",
    "I'm charged twice - didn't expect that! It's re: bill #42.",
    "multiple   spaces\ttabs\nnewlines\n\n\r\nend",
    " hello world",
    "hello world ",
    "trailing spaces   ",
    "   leading",
    "Mein Konto wurde zweimal belastet, bitte erstatten!",
    "O cliente foi cobrado duas vezes e quer reembolso agora.",
    "Donde esta mi reembolso? Lo necesito urgentemente!",
    "naive cafe resume Zurich ubermensch facade",
    "my account was charged twice",
    "refund please double charge",
    "a/b testing: 3.14 approx pi, x to y, 50% off!",
    "see https://github.com/Cyrax321/snapjudge and user@acme.com v1.2.3",
    ("The quick brown fox jumps over the lazy dog. " * 12).strip(),
    " ",
    "a",
]


def main():
    # A tiny deterministic char-level "ids" set so the tokenizer test can pin
    # exact ids from our tokenizer (generated by snapjudge itself; the C++ test
    # reads the fixture it produced — the fixture is written by a small C++
    # helper at build time; here we only pin TEXTS so the fixture generator and
    # the test share the *input* list).
    with open(os.path.join(OUT, "texts.json"), "w") as f:
        json.dump({"texts": TEXTS}, f, ensure_ascii=False, indent=1)

    # tensor op fixture (numpy only — no reference dependency)
    rng = np.random.default_rng(20260923)
    A = rng.standard_normal((7, 13), dtype=np.float32)
    W = rng.standard_normal((11, 13), dtype=np.float32) * 0.05
    B = rng.standard_normal((11,), dtype=np.float32) * 0.01
    from math import erf

    def gelu(x):
        return 0.5 * x * (1.0 + np.vectorize(erf)(x * 0.70710678118654757))

    cases = {
        "gemm": {"a": A.tolist(), "w": W.tolist(), "bias": B.tolist(),
                 "out": (A @ W.T + B).tolist()},
        "gemm_gelu": {"out": gelu(A @ W.T + B).tolist()},
        "gemm_relu": {"out": np.maximum(A @ W.T + B, 0).tolist()},
    }
    F = 9
    Wi = rng.standard_normal((2 * F, 13), dtype=np.float32) * 0.05
    z = A @ Wi.T
    cases["geglu"] = {"wi": Wi.tolist(), "out": (gelu(z[:, :F]) * z[:, F:]).tolist()}
    x = rng.standard_normal((5, 17), dtype=np.float32)
    w = rng.standard_normal((17,), dtype=np.float32)
    b = rng.standard_normal((17,), dtype=np.float32)
    def ln(x, w, b):
        m = x.mean(-1, keepdims=True)
        v = x.var(-1, keepdims=True)
        return (x - m) / np.sqrt(v + 1e-5) * w + (0 if b is None else b)
    cases["layer_norm"] = {"x": x.tolist(), "w": w.tolist(), "b": b.tolist(),
                           "out": ln(x, w, b).tolist(), "out_nobias": ln(x, w, None).tolist()}
    z2 = np.array([[0.0, 1.0, -1e4, 2.0], [3.0, 3.0, 3.0, 3.0], [1e4, 0.0, -1.0, -100.0]], dtype=np.float32)
    p = np.exp(z2 - z2.max(-1, keepdims=True))
    cases["softmax"] = {"z": z2.tolist(), "out": (p / p.sum(-1, keepdims=True)).tolist()}
    B_, H_, L_, Dh_ = 2, 3, 6, 4
    q = rng.standard_normal((B_, H_, L_, Dh_)).astype(np.float32) * 0.5
    k = rng.standard_normal((B_, H_, L_, Dh_)).astype(np.float32) * 0.5
    v = rng.standard_normal((B_, H_, L_, Dh_)).astype(np.float32)
    lens = [6, 4]

    def attn(q, k, v, lens, window):
        B, H, L, Dh = q.shape
        out = np.zeros_like(q)
        for bb in range(B):
            n = lens[bb]
            for h in range(H):
                for i in range(L):
                    idx = [j for j in range(L) if j < n and (window == 0 or abs(i - j) <= window)]
                    s = q[bb, h, i] @ k[bb, h, idx].T / np.sqrt(Dh)
                    p = np.exp(s - s.max())
                    p /= p.sum()
                    out[bb, h, i] = p @ v[bb, h, idx]
        return out
    cases["attn_full"] = {"q": q.tolist(), "k": k.tolist(), "v": v.tolist(),
                          "lens": lens, "window": 0, "out": attn(q, k, v, lens, 0).tolist()}
    cases["attn_window"] = {"window": 2, "out": attn(q, k, v, lens, 2).tolist()}
    M_, Lr, Hr, Dhr = 8, 4, 2, 6
    qkv = rng.standard_normal((M_, 3 * Hr * Dhr)).astype(np.float32)
    theta = 10000.0
    half = Dhr // 2
    inv_freq = 1.0 / (theta ** (np.arange(0, Dhr, 2, dtype=np.float64) / Dhr))
    pos = np.arange(Lr)
    freqs = np.outer(pos, inv_freq)
    cos_t, sin_t = np.cos(freqs), np.sin(freqs)
    out = qkv.copy().astype(np.float64)
    for r in range(M_):
        p_ = r % Lr
        for hh in range(2 * Hr):
            base = hh * Dhr
            x0 = out[r, base:base + half].copy()
            x1 = out[r, base + half:base + Dhr].copy()
            out[r, base:base + half] = x0 * cos_t[p_] - x1 * sin_t[p_]
            out[r, base + half:base + Dhr] = x1 * cos_t[p_] + x0 * sin_t[p_]
    cases["rope"] = {"qkv": qkv.tolist(), "L": Lr, "H": Hr, "Dh": Dhr,
                     "theta": theta, "out": out.tolist(),
                     "cos": cos_t.tolist(), "sin": sin_t.tolist()}
    with open(os.path.join(OUT, "tensor_ops.json"), "w") as f:
        json.dump(cases, f)
    print("wrote texts.json + tensor_ops.json")


if __name__ == "__main__":
    main()
