#include "snapjudge/metrics.hpp"

#include <algorithm>
#include <cmath>
#include <numeric>
#include <sstream>

#include "snapjudge/common.hpp"  // ece_score

namespace snapjudge {

namespace {

// Mann-Whitney AUROC: P(conf_positive > conf_negative) with tie handling.
double auroc(const std::vector<double>& conf, const std::vector<double>& correct) {
  std::vector<std::pair<double, double>> pairs;
  for (size_t i = 0; i < conf.size(); ++i) pairs.emplace_back(conf[i], correct[i]);
  std::sort(pairs.begin(), pairs.end());
  size_t n_pos = 0;
  for (auto& p : pairs) if (p.second >= 0.5) ++n_pos;
  size_t n = pairs.size(), n_neg = n - n_pos;
  if (!n_pos || !n_neg) return NAN;
  // rank-sum with average ranks for ties
  double rsum = 0;
  size_t i = 0;
  while (i < n) {
    size_t j = i;
    while (j < n && pairs[j].first == pairs[i].first) ++j;
    double avg_rank = (i + j + 1) / 2.0;  // 1-based
    for (size_t k = i; k < j; ++k) if (pairs[k].second >= 0.5) rsum += avg_rank;
    i = j;
  }
  return (rsum - n_pos * (n_pos + 1) / 2.0) / (n_pos * (double)n_neg);
}

// Spearman rank correlation of two vectors.
double spearman(std::vector<double> a, std::vector<double> b) {
  size_t n = a.size();
  if (n < 2) return NAN;
  auto rankify = [](std::vector<double> v) {
    std::vector<size_t> ix(v.size());
    std::iota(ix.begin(), ix.end(), 0);
    std::sort(ix.begin(), ix.end(), [&](size_t p, size_t q) { return v[p] < v[q]; });
    std::vector<double> r(v.size());
    size_t i = 0;
    while (i < ix.size()) {
      size_t j = i;
      while (j < ix.size() && v[ix[j]] == v[ix[i]]) ++j;
      double avg = (i + j - 1) / 2.0 + 1;
      for (size_t k = i; k < j; ++k) r[ix[k]] = avg;
      i = j;
    }
    return r;
  };
  auto ra = rankify(std::move(a)), rb = rankify(std::move(b));
  double ma = std::accumulate(ra.begin(), ra.end(), 0.0) / n;
  double mb = std::accumulate(rb.begin(), rb.end(), 0.0) / n;
  double num = 0, da = 0, db = 0;
  for (size_t i = 0; i < n; ++i) {
    num += (ra[i] - ma) * (rb[i] - mb);
    da += (ra[i] - ma) * (ra[i] - ma);
    db += (rb[i] - mb) * (rb[i] - mb);
  }
  if (da == 0 || db == 0) return NAN;
  return num / std::sqrt(da * db);
}

}  // namespace

Metrics compute_metrics(const std::vector<MetricPoint>& points) {
  Metrics m;
  m.n = (int)points.size();
  if (!m.n) return m;

  double brier = 0, soft = 0, tv = 0, nll = 0;
  std::vector<double> conf, corr;
  std::vector<double> expq, expt;  // score rows only
  int score_n = 0;
  double mae_sum = 0;

  for (const auto& p : points) {
    double b = 0, s = 0, tvd = 0, ce = 0;
    for (size_t j = 0; j < p.q.size(); ++j) {
      double d = p.q[j] - p.t[j];
      b += d * d;
      s += p.q[j] * p.t[j];
      tvd += std::fabs(d);
      ce += p.t[j] * std::log(std::max(p.q[j], 1e-12));
    }
    brier += b;
    soft += s;
    tv += tvd / 2;
    nll -= ce;
    conf.push_back(p.conf);
    corr.push_back(p.correct);
    if (p.qtype == 1) {
      double eq = 0, et = 0;
      for (size_t j = 0; j < p.q.size(); ++j) { eq += j * p.q[j]; et += j * p.t[j]; }
      mae_sum += std::fabs(eq - et);
      expq.push_back(eq);
      expt.push_back(et);
      ++score_n;
    }
  }
  m.brier = brier / m.n;
  m.soft = soft / m.n;
  m.tv = tv / m.n;
  m.nll = nll / m.n;
  m.ece = ece_score(conf, corr);
  m.accuracy = std::accumulate(corr.begin(), corr.end(), 0.0) / m.n;

  // MCE: max |bin_acc - bin_conf| over 15 bins
  {
    const int B = 15;
    double bc[15] = {0}, bn[15] = {0}, bcx[15] = {0};
    for (size_t i = 0; i < conf.size(); ++i) {
      int bb = std::min(B - 1, (int)(conf[i] * B));
      bc[bb] += corr[i];
      bcx[bb] += conf[i];
      bn[bb] += 1;
    }
    double mmax = 0;
    for (int b = 0; b < B; ++b)
      if (bn[b]) mmax = std::max(mmax, std::fabs(bc[b] / bn[b] - bcx[b] / bn[b]));
    m.mce = mmax;
  }
  m.auroc_conf = auroc(conf, corr);
  if (score_n) {
    m.score_mae = mae_sum / score_n;
    m.spearman = spearman(expq, expt);
  }
  return m;
}

std::map<std::string, std::pair<int, int>> accuracy_by_type(
    const std::vector<MetricPoint>& points) {
  std::map<std::string, std::pair<int, int>> out;
  const char* names[3] = {"choice", "score", "noul"};
  for (const auto& p : points) {
    auto& e = out[names[p.qtype]];
    e.first += p.correct >= 0.5 ? 1 : 0;
    ++e.second;
  }
  return out;
}

std::string metrics_latex(const Metrics& m, const std::string& ckpt_name) {
  std::ostringstream s;
  s.setf(std::ios::fixed);
  s.precision(4);
  s << "% snapjudge eval table — generated by snapjudge-plots\n"
       "\\begin{tabular}{lc}\n\\toprule\n"
       "\\multicolumn{2}{c}{" << ckpt_name << "} \\\\\n\\midrule\n";
  s << "Accuracy $\\uparrow$ & " << m.accuracy << " \\\\\n"
       "Soft score (q$\\cdot$t) $\\uparrow$ & " << m.soft << " \\\\\n"
       "TV distance $\\downarrow$ & " << m.tv << " \\\\\n"
       "NLL $\\downarrow$ & " << m.nll << " \\\\\n"
       "Brier $\\downarrow$ & " << m.brier << " \\\\\n"
       "ECE $\\downarrow$ & " << m.ece << " \\\\\n"
       "MCE $\\downarrow$ & " << m.mce << " \\\\\n"
       "AUROC (confidence $\\to$ correctness) $\\uparrow$ & " << m.auroc_conf << " \\\\\n";
  if (!std::isnan(m.score_mae)) s << "Score MAE $\\downarrow$ & " << m.score_mae << " \\\\\n";
  if (!std::isnan(m.spearman)) s << "Score Spearman $\\uparrow$ & " << m.spearman << " \\\\\n";
  s << "\\bottomrule\n\\end{tabular}\n";
  return s.str();
}

}  // namespace snapjudge
