#include "snapjudge/unicode.hpp"

#include <algorithm>
#include <cstddef>
#include <utility>

namespace snapjudge {

// ---- generated table types --------------------------------------------------
namespace unicode_tables {
struct Range { char32_t lo, hi; };
struct CaseMap { char32_t from; char32_t to[3]; uint8_t len; };
struct Decomp { char32_t from; char32_t to[2]; uint8_t len; };
struct CompPair { char32_t a, b, cp; };
struct CccEntry { char32_t cp; uint8_t ccc; };
}  // namespace unicode_tables

#include "unicode_tables.inc"  // generated by snapjudge/python/gen_unicode.py

namespace ut = unicode_tables;

static inline bool in_ranges(const ut::Range* r, size_t n, char32_t cp) {
  size_t lo = 0, hi = n;
  while (lo < hi) {
    size_t mid = (lo + hi) / 2;
    if (cp < r[mid].lo) hi = mid;
    else if (cp > r[mid].hi) lo = mid + 1;
    else return true;
  }
  return false;
}

static inline bool in_cps(const char32_t* a, size_t n, char32_t cp) {
  return std::binary_search(a, a + n, cp);
}

// ---- UTF-8 ------------------------------------------------------------------
char32_t utf8_decode_next(const std::string& s, size_t& i) {
  const unsigned char* p = reinterpret_cast<const unsigned char*>(s.data());
  unsigned char c0 = p[i];
  if (c0 < 0x80) { ++i; return c0; }
  auto bad = [&]() { ++i; return static_cast<char32_t>(0xFFFD); };
  int need = c0 >= 0xF0 ? 3 : c0 >= 0xE0 ? 2 : c0 >= 0xC0 ? 1 : 0;
  if (need == 0) return bad();
  if (i + need >= s.size()) return bad();
  char32_t cp = c0 & ((need == 1) ? 0x1F : (need == 2) ? 0x0F : 0x07);
  for (int k = 1; k <= need; ++k) {
    unsigned char ck = p[i + k];
    if ((ck & 0xC0) != 0x80) return bad();
    cp = (cp << 6) | (ck & 0x3F);
  }
  // overlong / surrogate / out-of-range checks
  if ((need == 1 && cp < 0x80) || (need == 2 && cp < 0x800) ||
      (need == 3 && (cp < 0x10000 || cp > 0x10FFFF)) ||
      (cp >= 0xD800 && cp <= 0xDFFF)) {
    return bad();
  }
  i += need + 1;
  return cp;
}

std::u32string utf8_decode(const std::string& s) {
  std::u32string out;
  out.reserve(s.size());
  size_t i = 0;
  while (i < s.size()) out.push_back(utf8_decode_next(s, i));
  return out;
}

std::string utf8_encode(char32_t cp) {
  std::string out;
  if (cp < 0x80) {
    out.push_back(static_cast<char>(cp));
  } else if (cp < 0x800) {
    out.push_back(static_cast<char>(0xC0 | (cp >> 6)));
    out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
  } else if (cp < 0x10000) {
    out.push_back(static_cast<char>(0xE0 | (cp >> 12)));
    out.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
    out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
  } else {
    out.push_back(static_cast<char>(0xF0 | (cp >> 18)));
    out.push_back(static_cast<char>(0x80 | ((cp >> 12) & 0x3F)));
    out.push_back(static_cast<char>(0x80 | ((cp >> 6) & 0x3F)));
    out.push_back(static_cast<char>(0x80 | (cp & 0x3F)));
  }
  return out;
}

std::string utf8_encode(const std::u32string& cps) {
  std::string out;
  for (char32_t cp : cps) out += utf8_encode(cp);
  return out;
}

// ---- properties -------------------------------------------------------------
bool uni_isalpha(char32_t cp) { return in_ranges(ut::ALPHA, ut::ALPHA_N, cp); }
bool uni_isletter(char32_t cp) { return in_ranges(ut::LETTER, ut::LETTER_N, cp); }
bool uni_isnumber(char32_t cp) { return in_ranges(ut::NUMBER, ut::NUMBER_N, cp); }
bool uni_isdigit(char32_t cp) { return in_cps(ut::DIGIT, ut::DIGIT_N, cp); }
bool uni_isspace(char32_t cp) { return in_ranges(ut::SPACE, ut::SPACE_N, cp); }
bool uni_isws(char32_t cp) { return in_ranges(ut::WS, ut::WS_N, cp); }
bool uni_isword(char32_t cp) { return in_ranges(ut::WORD, ut::WORD_N, cp); }
bool uni_iswordchar(char32_t cp) { return in_ranges(ut::WORDCHAR, ut::WORDCHAR_N, cp); }
bool uni_iscombining(char32_t cp) { return in_cps(ut::COMBINING, ut::COMBINING_N, cp); }

// ---- case -------------------------------------------------------------------
static const ut::CaseMap* find_case(const ut::CaseMap* m, size_t n, char32_t cp) {
  size_t lo = 0, hi = n;
  while (lo < hi) {
    size_t mid = (lo + hi) / 2;
    if (cp < m[mid].from) hi = mid;
    else if (cp > m[mid].from) lo = mid + 1;
    else return m + mid;
  }
  return nullptr;
}

char32_t uni_lower1(char32_t cp) {
  const ut::CaseMap* m = find_case(ut::LOWER, ut::LOWER_N, cp);
  return (m && m->len == 1) ? m->to[0] : cp;
}

bool uni_isupper(char32_t cp) { return find_case(ut::LOWER, ut::LOWER_N, cp) != nullptr; }

std::u32string uni_lower(const std::u32string& s) {
  std::u32string out;
  out.reserve(s.size());
  for (char32_t cp : s) {
    const ut::CaseMap* m = find_case(ut::LOWER, ut::LOWER_N, cp);
    if (m) for (uint8_t k = 0; k < m->len; ++k) out.push_back(m->to[k]);
    else out.push_back(cp);
  }
  return out;
}

std::u32string uni_upper(const std::u32string& s) {
  std::u32string out;
  out.reserve(s.size());
  for (char32_t cp : s) {
    const ut::CaseMap* m = find_case(ut::UPPER, ut::UPPER_N, cp);
    if (m) for (uint8_t k = 0; k < m->len; ++k) out.push_back(m->to[k]);
    else out.push_back(cp);
  }
  return out;
}

// ---- NFC --------------------------------------------------------------------
static uint8_t combining_class(char32_t cp) {
  const ut::CccEntry* c = ut::CCC;
  size_t lo = 0, hi = ut::CCC_N;
  while (lo < hi) {
    size_t mid = (lo + hi) / 2;
    if (cp < c[mid].cp) hi = mid;
    else if (cp > c[mid].cp) lo = mid + 1;
    else return c[mid].ccc;
  }
  return 0;
}

static void decompose_into(char32_t cp, std::u32string& out) {
  const ut::Decomp* d = ut::DECOMP;
  size_t lo = 0, hi = ut::DECOMP_N;
  while (lo < hi) {
    size_t mid = (lo + hi) / 2;
    if (cp < d[mid].from) hi = mid;
    else if (cp > d[mid].from) lo = mid + 1;
    else {
      for (uint8_t k = 0; k < d[mid].len; ++k) decompose_into(d[mid].to[k], out);
      return;
    }
  }
  out.push_back(cp);
}

static char32_t compose(char32_t a, char32_t b) {
  const ut::CompPair* c = ut::COMP;
  size_t lo = 0, hi = ut::COMP_N;
  while (lo < hi) {
    size_t mid = (lo + hi) / 2;
    const ut::CompPair& e = c[mid];
    if (a < e.a || (a == e.a && b < e.b)) hi = mid;
    else if (a > e.a || (a == e.a && b > e.b)) lo = mid + 1;
    else return e.cp;
  }
  return 0;
}

std::u32string nfc(const std::u32string& s) {
  // 1. full canonical decomposition
  std::u32string d;
  d.reserve(s.size());
  for (char32_t cp : s) decompose_into(cp, d);
  // 2. canonical ordering (stable insertion sort by combining class)
  for (size_t i = 1; i < d.size(); ++i) {
    uint8_t ci = combining_class(d[i]);
    if (ci == 0) continue;
    size_t j = i;
    while (j > 0 && combining_class(d[j - 1]) > ci) {
      std::swap(d[j], d[j - 1]);
      --j;
    }
  }
  // 3. recompose: track last starter, try to compose with each following char.
  std::u32string out;
  out.reserve(d.size());
  size_t starter = 0;      // index of last starter in out
  bool have_starter = false;
  uint8_t last_cc = 0;
  for (char32_t cp : d) {
    uint8_t cc = combining_class(cp);
    if (have_starter && (cc == 0 ? true : last_cc < cc)) {
      if (char32_t c = compose(out[starter], cp)) {
        out[starter] = c;
        if (cc == 0) last_cc = 0;  // composed starter stays the starter
        continue;                  // cc != 0: do not advance last_cc
      }
    }
    out.push_back(cp);
    if (cc == 0) { starter = out.size() - 1; have_starter = true; last_cc = 0; }
    else last_cc = cc;
  }
  return out;
}

std::string nfc(const std::string& utf8) { return utf8_encode(nfc(utf8_decode(utf8))); }

}  // namespace snapjudge
